# language: ruby
# cache: bundler
# gemfile: docs/Gemfile
# script:
#   - bundle exec jekyll algolia --source docs --destination docs/_site --config docs/_config.yml
# branches:
#   only:
#     # Change this to gh-pages if you're deploying using the gh-pages branch
#     - master
# rvm:
#  - 2.4

# .travis.yml
# This file should be at the root of your project
language: ruby
cache: bundler
before_install:
  - gem install bundler
script:
  - ALGOLIA_API_KEY='e4379bff763553e499f66b15934ca300' bundle exec jekyll algolia
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4
